name: 'SCP Command to Transfer Files'
description: 'How to Use SCP Command to Transfer Files/Folders in Linux'
author: 'Bo-Yi Wu'
inputs:
  host:
    description: 'scp remote host'
  port:
    description: 'scp remote port'
    default: 22
  username:
    description: 'scp username'
  password:
    description: 'scp password'
  timeout:
    description: 'timeout for ssh to remote host'
    default: "30s"
  command_timeout:
    description: 'timeout for scp command'
    default: "10m"
  key:
    description: 'content of ssh private key. ex raw content of ~/.ssh/id_rsa'
  key_path:
    description: 'path of ssh private key'
  passphrase:
    description: 'ssh key passphrase'
  target:
    description: 'target path on the server'
  source:
    description: 'scp file list'
  rm:
    description: 'remove target folder before upload data'
  strip_components:
    description: 'remove the specified number of leading path elements'
    default: 0
  overwrite:
    description: 'use `--overwrite` flag with tar'
    default: false
  tar_tmp_path:
    description: 'temporary path for tar file on the dest host'
  proxy_host:
    description: 'ssh proxy remote host'
  proxy_port:
    description: 'ssh proxy remote port'
    default: 22
  proxy_username:
    description: 'ssh proxy username'
  proxy_password:
    description: 'ssh proxy password'
  proxy_passphrase:
    description: 'ssh proxy key passphrase'
  proxy_timeout:
    description: 'timeout for ssh to proxy host'
    default: "30s"
  proxy_key:
    description: 'content of ssh proxy private key. ex raw content of ~/.ssh/id_rsa'
  proxy_key_path:
    description: 'path of ssh proxy private key'
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'copy'
  color: 'gray-dark'
